# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
require 'webmock/rspec'
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://rspec.info/features/3-12/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end

def learning_resource_laos
  {
    "data": {
        "id": nil,
        "type": "learning_resource",
        "attributes": {
            "country": "laos",
            "video": {
                "title": "A Super Quick History of Laos",
                "youtube_video_id": "uw8hjVqxMXw"
            },
            "images": [
                {
                    "url": "https://images.unsplash.com/photo-1540611025311-01df3cef54b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHwxfHxsYW9zfGVufDB8fHx8MTY5MTM1OTY3Nnww&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "time lapse photography of flying hot air balloon"
                },
                {
                    "url": "https://images.unsplash.com/photo-1570366583862-f91883984fde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHwyfHxsYW9zfGVufDB8fHx8MTY5MTM1OTY3Nnww&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "aerial view of city at daytime"
                },
                {
                    "url": "https://images.unsplash.com/photo-1610426714962-83caa2244105?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHwzfHxsYW9zfGVufDB8fHx8MTY5MTM1OTY3Nnww&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "brown and white concrete building under blue sky during daytime"
                },
                {
                    "url": "https://images.unsplash.com/photo-1593994602962-fc4c26fd82e9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHw0fHxsYW9zfGVufDB8fHx8MTY5MTM1OTY3Nnww&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "aerial view of green trees and mountains during daytime"
                },
                {
                    "url": "https://images.unsplash.com/photo-1441632260885-881646a7fd4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHw1fHxsYW9zfGVufDB8fHx8MTY5MTM1OTY3Nnww&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "two boats near body of water"
                },
                {
                    "url": "https://images.unsplash.com/photo-1626982024771-282582a4ecac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHw2fHxsYW9zfGVufDB8fHx8MTY5MTM1OTY3Nnww&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "waterfalls in the middle of the forest during daytime"
                },
                {
                    "url": "https://images.unsplash.com/photo-1565092640981-0081b99f45ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHw3fHxsYW9zfGVufDB8fHx8MTY5MTM1OTY3Nnww&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "waterfalls on mountain"
                },
                {
                    "url": "https://images.unsplash.com/photo-1608000065495-0032a4e54f80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHw4fHxsYW9zfGVufDB8fHx8MTY5MTM1OTY3Nnww&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "woman in red and white floral dress smiling"
                },
                {
                    "url": "https://images.unsplash.com/photo-1606064195579-a48c728cec35?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHw5fHxsYW9zfGVufDB8fHx8MTY5MTM1OTY3Nnww&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "green trees near body of water during daytime"
                },
                {
                    "url": "https://images.unsplash.com/photo-1553856622-d1b352e9a211?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w0ODU0Njl8MHwxfHNlYXJjaHwxMHx8bGFvc3xlbnwwfHx8fDE2OTEzNTk2NzZ8MA&ixlib=rb-4.0.3&q=80&w=1080",
                    "alt_tag": "body of water during sunset"
                }
            ]
        }
    }
}
end
